baseURL = "https://sleepy-caverns-57661.herokuapp.com/blog/"
languageCode = "en-us"
theme = "chunky-poster"
title = "School Desk"
publishDir = "blog_out"

archetypeDir = "blog/archetypes"
contentDir = "blog/content"
data = "blog/data"
layoutDir = "blog/layouts"
staticDir = "blog/static"
themesDir = "blog/themes"

# Chunky Poster theme stuff
paginate = 2
footnoteReturnLinkContents = "^"

[menu]
[[menu.main]]
identifier = "home"
name = "Return To App â‡’"
url = "https://sleepy-caverns-57661.herokuapp.com/"
weight = 10

[taxonomies]
author = "authors"
tag = "tags"
category = "categories"

[params]
description = "Homeschool Planning Simplified"
share = true
# homepageImage = "/static/logo.svg"

[params.social]
rss = true
